//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crossover.app.CrossoverSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrossoverSvc.StockSvcSoap")]
    public interface StockSvcSoap {
        
        // CODEGEN: Generating message contract since message AuthenticateUserRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Crossover.app.CrossoverSvc.AuthenticateUserResponse AuthenticateUser(Crossover.app.CrossoverSvc.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Crossover.app.CrossoverSvc.AuthenticateUserResponse> AuthenticateUserAsync(Crossover.app.CrossoverSvc.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        // CODEGEN: Generating message contract since message GetStockPriceRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStockPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Crossover.app.CrossoverSvc.GetStockPriceResponse GetStockPrice(Crossover.app.CrossoverSvc.GetStockPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStockPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<Crossover.app.CrossoverSvc.GetStockPriceResponse> GetStockPriceAsync(Crossover.app.CrossoverSvc.GetStockPriceRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SecuredWebServiceHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string authenticatedTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AuthenticatedToken {
            get {
                return this.authenticatedTokenField;
            }
            set {
                this.authenticatedTokenField = value;
                this.RaisePropertyChanged("AuthenticatedToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Crossover.app.CrossoverSvc.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(Crossover.app.CrossoverSvc.SecuredWebServiceHeader SecuredWebServiceHeader) {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string AuthenticateUserResult;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(string AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStockPrice", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStockPriceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Crossover.app.CrossoverSvc.SecuredWebServiceHeader SecuredWebServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string exchange;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string symbol;
        
        public GetStockPriceRequest() {
        }
        
        public GetStockPriceRequest(Crossover.app.CrossoverSvc.SecuredWebServiceHeader SecuredWebServiceHeader, string exchange, string symbol) {
            this.SecuredWebServiceHeader = SecuredWebServiceHeader;
            this.exchange = exchange;
            this.symbol = symbol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStockPriceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStockPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double GetStockPriceResult;
        
        public GetStockPriceResponse() {
        }
        
        public GetStockPriceResponse(double GetStockPriceResult) {
            this.GetStockPriceResult = GetStockPriceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockSvcSoapChannel : Crossover.app.CrossoverSvc.StockSvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockSvcSoapClient : System.ServiceModel.ClientBase<Crossover.app.CrossoverSvc.StockSvcSoap>, Crossover.app.CrossoverSvc.StockSvcSoap {
        
        public StockSvcSoapClient() {
        }
        
        public StockSvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockSvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockSvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockSvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Crossover.app.CrossoverSvc.AuthenticateUserResponse Crossover.app.CrossoverSvc.StockSvcSoap.AuthenticateUser(Crossover.app.CrossoverSvc.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public string AuthenticateUser(Crossover.app.CrossoverSvc.SecuredWebServiceHeader SecuredWebServiceHeader) {
            Crossover.app.CrossoverSvc.AuthenticateUserRequest inValue = new Crossover.app.CrossoverSvc.AuthenticateUserRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            Crossover.app.CrossoverSvc.AuthenticateUserResponse retVal = ((Crossover.app.CrossoverSvc.StockSvcSoap)(this)).AuthenticateUser(inValue);
            return retVal.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Crossover.app.CrossoverSvc.AuthenticateUserResponse> Crossover.app.CrossoverSvc.StockSvcSoap.AuthenticateUserAsync(Crossover.app.CrossoverSvc.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Crossover.app.CrossoverSvc.AuthenticateUserResponse> AuthenticateUserAsync(Crossover.app.CrossoverSvc.SecuredWebServiceHeader SecuredWebServiceHeader) {
            Crossover.app.CrossoverSvc.AuthenticateUserRequest inValue = new Crossover.app.CrossoverSvc.AuthenticateUserRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            return ((Crossover.app.CrossoverSvc.StockSvcSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Crossover.app.CrossoverSvc.GetStockPriceResponse Crossover.app.CrossoverSvc.StockSvcSoap.GetStockPrice(Crossover.app.CrossoverSvc.GetStockPriceRequest request) {
            return base.Channel.GetStockPrice(request);
        }
        
        public double GetStockPrice(Crossover.app.CrossoverSvc.SecuredWebServiceHeader SecuredWebServiceHeader, string exchange, string symbol) {
            Crossover.app.CrossoverSvc.GetStockPriceRequest inValue = new Crossover.app.CrossoverSvc.GetStockPriceRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.exchange = exchange;
            inValue.symbol = symbol;
            Crossover.app.CrossoverSvc.GetStockPriceResponse retVal = ((Crossover.app.CrossoverSvc.StockSvcSoap)(this)).GetStockPrice(inValue);
            return retVal.GetStockPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Crossover.app.CrossoverSvc.GetStockPriceResponse> Crossover.app.CrossoverSvc.StockSvcSoap.GetStockPriceAsync(Crossover.app.CrossoverSvc.GetStockPriceRequest request) {
            return base.Channel.GetStockPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Crossover.app.CrossoverSvc.GetStockPriceResponse> GetStockPriceAsync(Crossover.app.CrossoverSvc.SecuredWebServiceHeader SecuredWebServiceHeader, string exchange, string symbol) {
            Crossover.app.CrossoverSvc.GetStockPriceRequest inValue = new Crossover.app.CrossoverSvc.GetStockPriceRequest();
            inValue.SecuredWebServiceHeader = SecuredWebServiceHeader;
            inValue.exchange = exchange;
            inValue.symbol = symbol;
            return ((Crossover.app.CrossoverSvc.StockSvcSoap)(this)).GetStockPriceAsync(inValue);
        }
    }
}
